import { ReactNode } from 'react';
import Link from 'next/link';
import { WalletButton } from '../solana/solana-provider';


export function AppLayout({ children }: { children: ReactNode }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '6px 12px',
          textDecoration: 'none',
        }}
      >
        <div>
          <Link href="/">
            <img src="/sol-stripe-logo.png" height={64} alt="SolStripe Logo" />
          </Link>
        </div>
        <div>

        <Link href="/" style={{
          textDecoration: 'none',
        }}>Limit Order</Link>

        </div>
        <div>

        <Link href="/buycrypto" style={{
          textDecoration: 'none',
        }}>Buy/Sell Crypto</Link>

        </div>
        <div>

        <Link href="/transactions" style={{
          textDecoration: 'none',
        }}>View Transactions</Link>

        </div>
        <div>
          <WalletButton />
        </div>
      </div>
      <div style={{ flexGrow: 1, padding: '6px' }}>{children}</div>
      <footer
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '6px 10px',
        }}
      >
        <aside>
          {/* <p>
            Generated by{' '}
            <a
              href="https://github.com/solana-developers/create-solana-dapp"
              target="_blank"
              rel="noopener noreferrer"
            >
              create-solana-dapp
            </a>
          </p> */}
        </aside>
      </footer>
    </div>
  );
}
